# Generated by Django 5.1.2 on 2024-11-27 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-time_create']},
        ),
        migrations.RemoveField(
            model_name='post',
            name='attached_files',
        ),
        migrations.AlterField(
            model_name='post',
            name='is_published',
            field=models.BooleanField(choices=[(0, 'Private'), (1, 'Published')], default=1),
        ),
        migrations.AlterField(
            model_name='postfiles',
            name='id_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-time_create'], name='posts_post_time_cr_e5aa17_idx'),
        ),
    ]
