# Generated by Django 5.1.2 on 2024-11-28 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_rename_id_post_postfiles_post_remove_post_id_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='author',
        ),
    ]
